# Generated by Django 6.0.3 on 2026-03-17 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('habbit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habit',
            new_name='Habbit',
        ),
    ]
